# Options for analysis running
# More info could be found at https://golangci-lint.run/usage/configuration/
run:
    # timeout for analysis, e.g. 30s, 5m, default is 1m
    timeout: 5m
    modules-download-mode: readonly

# List of useful linters could be found at https://github.com/golangci/awesome-go-linters
linters:
    disable-all: true
    enable:
        - errcheck
        - exportloopref
        # - depguard
        #    - gci
        - gofumpt
        - goimports
        - gosimple
        - govet
        - ineffassign
        - makezero
        - megacheck
        - misspell
        - noctx
        - nolintlint
        #    - revive
        - rowserrcheck
        - sqlclosecheck
        - staticcheck
        #    - stylecheck
        - unconvert
        - unused
        - wastedassign

linters-settings:
    staticcheck:
        # https://staticcheck.io/docs/options#checks
        checks: [ "all","-SA1019","-SA1029" ]

issues:
    exclude-use-default: false
    # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
    max-issues-per-linter: 0
    # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
    max-same-issues: 0
